INSERT INTO METRIC_ALERT (CODE, VALUE) VALUES ('CPU', 'High CPU');
INSERT INTO METRIC_ALERT (CODE, VALUE) VALUES ('MEMORY', 'High Memory');

--INSERT INTO GROUP_ALERT (NAME, ID_METRIC) VALUES ('ALERT CPU', (SELECT ID_METRIC FROM METRIC WHERE CODE = 'CPU'));
--INSERT INTO GROUP_ALERT (NAME, ID_METRIC) VALUES ('ALERT MEMORY', (SELECT ID_METRIC FROM METRIC WHERE CODE = 'MEMORY'));

INSERT INTO GROUP_ALERT_SCHEDULE (TIME_START, TIME_END) VALUES ('00:00:00.0000', '07:59:59.9999');
INSERT INTO GROUP_ALERT_SCHEDULE (TIME_START, TIME_END) VALUES ('08:00:00.0000', '15:59:59.9999');
INSERT INTO GROUP_ALERT_SCHEDULE (TIME_START, TIME_END) VALUES ('16:00:00.0000', '23:59:59.9999');

INSERT INTO GROUP_ALERT (NAME, ID_METRIC, ID_GROUP_SCHEDULE, EMAIL, SLACK_WEBHOOK, SLACK_ENDPOINT, DEFAULT_ALERT) VALUES ('ALERT SCHEDULE 1 CPU', 1, 1, 'lkr.junior@gmail.com', 'https://hooks.slack.com/services/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', 'slack:#trabalho-camel?username=alerta_gerado', false);
INSERT INTO GROUP_ALERT (NAME, ID_METRIC, ID_GROUP_SCHEDULE, EMAIL, SLACK_WEBHOOK, SLACK_ENDPOINT, DEFAULT_ALERT) VALUES ('ALERT SCHEDULE 2 CPU', 1, 2, 'lkr.junior@gmail.com', 'https://hooks.slack.com/services/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', 'slack:#trabalho-camel?username=alerta_gerado', false);
INSERT INTO GROUP_ALERT (NAME, ID_METRIC, ID_GROUP_SCHEDULE, EMAIL, SLACK_WEBHOOK, SLACK_ENDPOINT, DEFAULT_ALERT) VALUES ('ALERT SCHEDULE 3 CPU', 1, 3, 'lkr.junior@gmail.com', 'https://hooks.slack.com/services/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', 'slack:#trabalho-camel?username=alerta_gerado', false);
INSERT INTO GROUP_ALERT (NAME, ID_METRIC, ID_GROUP_SCHEDULE, EMAIL, SLACK_WEBHOOK, SLACK_ENDPOINT, DEFAULT_ALERT) VALUES ('ALERT SCHEDULE 1 MEMORY', 2, 1, 'lkr.junior@gmail.com', 'https://hooks.slack.com/services/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', 'slack:#trabalho-camel?username=alerta_gerado', false);
INSERT INTO GROUP_ALERT (NAME, ID_METRIC, ID_GROUP_SCHEDULE, EMAIL, SLACK_WEBHOOK, SLACK_ENDPOINT, DEFAULT_ALERT) VALUES ('ALERT SCHEDULE 2 MEMORY', 2, 2, 'lkr.junior@gmail.com', 'https://hooks.slack.com/services/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', 'slack:#trabalho-camel?username=alerta_gerado', false);
INSERT INTO GROUP_ALERT (NAME, ID_METRIC, ID_GROUP_SCHEDULE, EMAIL, SLACK_WEBHOOK, SLACK_ENDPOINT, DEFAULT_ALERT) VALUES ('ALERT SCHEDULE 3 MEMORY', 2, 3, 'lkr.junior@gmail.com', 'https://hooks.slack.com/services/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', 'slack:#trabalho-camel?username=alerta_gerado', false);
INSERT INTO GROUP_ALERT (NAME, ID_METRIC, ID_GROUP_SCHEDULE, EMAIL, SLACK_WEBHOOK, SLACK_ENDPOINT, DEFAULT_ALERT) VALUES ('ALERT DEFAULT', NULL, NULL, 'lkr.junior@gmail.com', 'https://hooks.slack.com/services/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', 'slack:#trabalho-camel?username=alerta_gerado', true);

INSERT INTO USER_ALERT (NAME, ID_GROUP) VALUES ('Luciano Rocha', 1);